<a href="https://colab.research.google.com/github/ajimenez-gh/cursophyton25/blob/main/Proyecto_3_admision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

ruta_archivo = '/content/drive/MyDrive/Colab Data/applicant_list_7.txt'

nombres_columnas = ['Nombre','Apellido','EPH','ECH','EMA','ECS','ESP','OP1','OP2','OP3']

df = pd.read_csv(ruta_archivo, sep=' ', names=nombres_columnas)
df

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech
...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics

In [ ]:
print(df.shape)
df.info()
display(df[['OP1', OP2','OP3']])

SyntaxError: unterminated string literal (detected at line 3) (ipython-input-3976588444.py, line 3)

In [ ]:
df['nombre_completo'] = df['Nombre'] + ' ' + df['Apellido']
df

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,nombre_completo
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics,Jermine Brunton
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry,Justo Mirfin
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics,Uzma Naysmythe
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics,Koury Wingo
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,Kentrell Hillhouse
...,...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics,Tamkia Fish
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry,Deniz Blanchard
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics,Mira Riley
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics,Loura Macansh
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,Nastassja Trustram

In [ ]:
# definicion de una funcion paraestimar puntaje de admisión
def estimar_puntaje_admision(linea, opcion):
  departamento = linea[opcion]
  if departamento == 'Physics':
    puntaje = (linea['EPH'] + linea['EMA'] + linea['ESP'])/3
  elif departamento == 'Chemistry':
    puntaje = (linea['ECH'] + linea['EPH'] + linea['ESP'])/3
  elif departamento ==  'Mathematics':
    puntaje = (linea['EMA'] + linea['EPH'] + linea['ECH']+ linea['ESP'])/4
  elif departamento ==  'Engineering':
    puntaje = (linea['ECH'] + linea['ECS'] + linea['EPH']+ linea['ESP'])/4
  elif departamento ==  'Biotech':
    puntaje = (linea['EMA'] + linea['ECS'] + linea['ECH']+ linea['ESP'])/4
  else:
    return None
  return round(puntaje,2)

df['OP1_score'] = df.apply(lambda x: estimar_puntaje_admision(x, 'OP1'), axis=1)
df['OP2_score'] = df.apply(lambda x: estimar_puntaje_admision(x, 'OP2'), axis=1)
df['OP3_score'] = df.apply(lambda x: estimar_puntaje_admision(x, 'OP3'), axis=1)
df

display(df)

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,nombre_completo,OP1_score,OP2_score,OP3_score
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics,Jermine Brunton,68.33,76.25,71.50
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry,Justo Mirfin,62.25,59.75,63.00
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics,Uzma Naysmythe,78.00,76.25,77.25
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics,Koury Wingo,73.50,76.00,73.00
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,Kentrell Hillhouse,42.75,46.75,47.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics,Tamkia Fish,77.33,79.00,75.75
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry,Deniz Blanchard,67.25,64.75,69.67
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics,Mira Riley,76.25,80.00,77.25
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics,Loura Macansh,81.00,77.00,78.00
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,Nastassja Trustram,65.25,61.75,70.67

In [ ]:
N = int(input("Ingrese el cupo máximo por departamento: "))
departamento_seleccionado = input("Ingrese el departamento a seleccionar: ")

Ingrese el cupo máximo por departamento: 10
Ingrese el departamento a seleccionar: Biotech

In [ ]:
#filtrado del data para seleccionar departamento
aspirantes_departamento = df[(df['OP1'] == departamento_seleccionado)]

aspirantes_ordenado = aspirantes_departamento.sort_values(by='OP1_score', ascending=False)
aspirantes_ordenado
aspirantes_ordenado.head(N)

tabla_aspirantes_admitidos = pd.DataFrame(

    {
        'nombre_completo': tabla.aspirantes_ordenado['nombre_completo'],
        'OP1_score': tabla.aspirantes_admitidos['OP1_score'],
        'puntaje': tabla_aspirantes_admitidos['OP1_score'],
        'opción': 'OP1'

    }
)
display(tabla_en_formato)


    aspirantes_ordenado.head(N))
tabla_en_formato = pd.DataFrame(tabla_aspirantes_admitidos[['nombre_completo','OP1_score']])
tabla_en_formato

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,nombre_completo,OP1_score,OP2_score,OP3_score
31,Tawnia,Alcock,81,80,90,72,91,Biotech,Chemistry,Physics,Tawnia Alcock,83.25,84.00,87.33
43,Genee,Mccrae,90,81,80,72,94,Biotech,Chemistry,Physics,Genee Mccrae,81.75,88.33,88.00
51,Randon,Bradhust,72,88,85,83,59,Biotech,Engineering,Chemistry,Randon Bradhust,78.75,75.50,73.00
67,Narissa,Worthington,52,71,80,73,81,Biotech,Chemistry,Mathematics,Narissa Worthington,76.25,68.00,NaN
76,Mendy,Macmillan,61,81,81,70,51,Biotech,Engineering,Mathematics,Mendy Macmillan,70.75,65.75,NaN